[build]
  command = "hugo --buildFuture"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.120.4"

[[redirects]]
  from = "https://caryleetenor.netlify.app/*"
  to = "https://caryleetenor.com/:splat"
  status = 301
  force = true
